name: 🐛 Bug Report
description: Create a report to help us improve the codemods
title: "bug: "

body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Code Reproduction URL
      description: If you can provide a sample application to reproduce this issue. This is the best way to ensure this issue is triaged quickly. Issues without a code reproduction may be closed if the Ionic Team cannot reproduce the issue you are reporting.
      placeholder: https://github.com/...

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
