import { describe, expect, it } from "vitest";
import { Project } from "ts-morph";
import { dedent } from "ts-dedent";

import { initializeAddIcons } from "./0000-initialize-add-icons";
import { cwd } from "node:process";

describe("initializeAddIcons", () => {
  it("initialize add icons to file", async () => {
    const project = new Project({ useInMemoryFileSystem: true });

    const appModuleSourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
      import { environment } from './environments/environment';
      
      if (environment.production) {
        enableProdMode();
      }
      
      bootstrapApplication(AppComponent, {
        providers: [
          { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
          provideIonicAngular(),
          provideRouter(routes),
        ],
      });
      `),
    );

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: true,
    });

    expect(dedent(appModuleSourceFile.getText())).toBe(
      dedent(`
      import { environment } from './environments/environment';
      import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";
      import * as useIcons from "./use-icons";
      
      if (environment.production) {
        enableProdMode();
      }
      void initializeIonicons(useIcons);
      
      bootstrapApplication(AppComponent, {
        providers: [
          { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
          provideIonicAngular(),
          provideRouter(routes),
        ],
      });
      `),
    );
  });

  it("replaces an unused addIcons import during initialization", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";

        if (environment.production) {
          enableProdMode();
        }
      `),
    );

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: true,
    });

    expect(dedent(sourceFile.getText())).toBe(
      dedent(`
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";
        import * as useIcons from "./use-icons";

        if (environment.production) {
          enableProdMode();
        }
        void initializeIonicons(useIcons);
      `),
    );
  });

  it("migrates a legacy nested generated icon import", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "icons/use-icons";

        addIcons(environment.production ? useIcons : allIcons);
      `),
    );

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/icons/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: true,
    });

    expect(dedent(sourceFile.getText())).toBe(
      dedent(`
        import * as useIcons from "./icons/use-icons";
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";

        void initializeIonicons(useIcons);
      `),
    );
  });

  it("migrates the initializer generated by older releases after approval", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "use-icons";

        addIcons(environment.production ? useIcons : allIcons);
      `),
    );

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: true,
    });

    expect(dedent(sourceFile.getText())).toBe(
      dedent(`
        import * as useIcons from "./use-icons";
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";

        void initializeIonicons(useIcons);
      `),
    );
  });

  it("requires permission without changing a legacy initializer", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "use-icons";

        addIcons(environment.production ? useIcons : allIcons);
      `),
    );
    const before = sourceFile.getText();

    const result = await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
    });

    expect(result).toBe("permission-required");
    expect(sourceFile.getText()).toBe(before);
  });

  it("honors an explicit migration decline", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "use-icons";

        addIcons(environment.production ? useIcons : allIcons);
      `),
    );
    const before = sourceFile.getText();

    const result = await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: false,
    });

    expect(result).toBe("declined");
    expect(sourceFile.getText()).toBe(before);
  });

  it("only migrates addIcons(useIcons) when migration is explicitly approved", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as useIcons from "./use-icons";

        addIcons(useIcons);
      `),
    );
    const options = {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
    };

    await initializeAddIcons(project, options);
    expect(dedent(sourceFile.getText())).toContain("addIcons(useIcons);");

    await initializeAddIcons(project, { ...options, migrate: true });
    expect(dedent(sourceFile.getText())).toBe(
      dedent(`
        import * as useIcons from "./use-icons";
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";

        void initializeIonicons(useIcons);
      `),
    );
  });

  it("does not migrate addIcons(useIcons) from a custom module", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as useIcons from "./custom-icons";

        addIcons(useIcons);
      `),
    );
    const before = sourceFile.getText();

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: true,
    });

    expect(sourceFile.getText()).toBe(before);
  });

  it.each([
    "initializeIonicons(useIcons);",
    "void initializeIonicons(useIcons);",
    "await initializeIonicons(useIcons);",
  ])("recognizes an existing initializer: %s", async (call) => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";
        import * as useIcons from "./use-icons";

        ${call}
      `),
    );
    const before = sourceFile.getText();

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: true,
    });

    expect(sourceFile.getText()).toBe(before);
  });

  it("does not rewrite a custom addIcons call", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      `import { addIcons } from "ionicons";\naddIcons({ custom: "svg" });`,
    );
    const before = sourceFile.getText();

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: true,
    });

    expect(sourceFile.getText()).toBe(before);
  });

  it("preserves imports used by custom code next to a legacy initializer", async () => {
    const project = new Project({ useInMemoryFileSystem: true });
    const sourceFile = project.createSourceFile(
      cwd() + "/src/main.ts",
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "./use-icons";

        addIcons(environment.production ? useIcons : allIcons);
        addIcons({ custom: "svg" });
        console.info(Object.keys(allIcons).length);
      `),
    );

    await initializeAddIcons(project, {
      dryRun: false,
      iconPath: "src/use-icons.ts",
      projectPath: cwd(),
      interactive: false,
      initialize: false,
      migrate: true,
    });

    expect(dedent(sourceFile.getText())).toBe(
      dedent(`
        import { addIcons } from "ionicons";
        import * as allIcons from "ionicons/icons";
        import * as useIcons from "./use-icons";
        import { initializeIonicons } from "@rdlabo/ionic-angular-collect-icons/runtime";

        void initializeIonicons(useIcons);
        addIcons({ custom: "svg" });
        console.info(Object.keys(allIcons).length);
      `),
    );
  });
});
